server:
  port: 8080


# spring配置
spring:
  thymeleaf:
    cache: false
  output:
    ansi:
      enabled: always
#spring-redis配置
  redis:
    client-name: lettuce-client
    database: 0
    host: 192.168.91.128
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 0        # 连接池中的最小空闲连接
        max-idle: 8        # 连接池中的最大空闲连接
        max-wait: -1       # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 20     # 连接池最大连接数（使用负值表示没有限制）

#actuator配置
management:
    endpoints:
      web:
        exposure:
          include: '*'        # 打开所有的监控端点

